name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches: [devel]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  build-server:
    name: Check / Build Java
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      MAVEN_OPTS: -Xmx2048m
    steps:
      - uses: actions/checkout@v4
        with:
          path: cloudbeaver

      - name: Clone dependencies
        run: |
          git clone --depth 1 -b main https://github.com/scalar-labs/dbeaver.git
          git clone --depth 1 -b main https://github.com/scalar-labs/dbeaver-common.git
          git clone --depth 1 https://github.com/dbeaver/dbeaver-jdbc-libsql.git

      - uses: dbeaver/github-actions/install-maven@devel

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
          cache-dependency-path: '**/pom.xml'

      - name: Build
        run: mvn clean verify -B -T1C -Dplain-api-server -Dheadless-platform
        working-directory: ./cloudbeaver/server/product/aggregate

  build-frontend:
    name: Frontend
    uses: ./.github/workflows/frontend-build.yml
    secrets: inherit

  lint-server:
    name: Server
    uses: scalar-labs/dbeaver-common/.github/workflows/java-checkstyle.yml@main
    secrets: inherit

  lint-frontend:
    name: Frontend
    uses: ./.github/workflows/frontend-lint.yml
    secrets: inherit

  # call-frontend-tests:
  #   name: Frontend Unit Tests
  #   needs: call-frontend-build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check if tests passed
  #       if: ${{ needs.call-frontend-build.outputs.test-status != 'success' }}
  #       run: |
  #         echo "Tests failed"
  #         exit 1
  #     - name: Continue if tests passed
  #       if: ${{ needs.call-frontend-build.outputs.test-status == 'success' }}
  #       run: echo "Tests passed"

  # call-docker-build-and-push:
  #   name: Run
  #   needs: [call-backend-build, call-frontend-build]
  #   uses: ./.github/workflows/docker-build-and-push.yml
